name: pos_sq
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
 
    
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  http: ^1.1.0
  intl: ^0.18.1
  path: ^1.8.3
  pdf: ^3.10.4
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.3.0

    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
