name: pos_sq
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
 
    
  cached_network_image: ^3.2.3
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  http: ^1.1.0
  intl: ^0.18.1
  path: ^1.8.3
  pdf: ^3.10.4
  visibility_detector: ^0.4.0+2
  drift: ^2.11.1
  sqlite3_flutter_libs: ^0.5.16
  path_provider: ^2.1.1
  drift_db_viewer: ^2.0.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.11.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
